### ISSUE TITLE
Overwriting Data stored as ByteIO

### ISSUE THREAD

**Issue by GeniviAMmaintainer** [samokhodkin/whippet-db#2]
I ran into an issue when using the database with a builder like this:

``` Kotlin
mBuilder = DbBuilder(CharsIO(), BytesIO()).also { builder ->
  mDatabase = builder
  .autoflush(true)
  .journaling(false)
  .synchronize(true)
  .openOrCreate(mContext.getDatabasePath("dbName").absolutePath).asMap()
}
```
I store data, read it again -> everything is fine.
But when I overwrite the data by setting a new value I get back garbage the next time I read it. When I delete the key before I rewrite it, everything is fine.
It seems to me that the size of bytes is not reduced when overwriting.

Is that to be expected or a real issue?

**Comment by samokhodkin** [comment]
Please, send a full example.

**Comment by GeniviAMmaintainer** [comment]
Sure. So I wrote these tests:
```Kotlin
class WhippetDBTest {

    @Test
    fun overwriteValue() {
        DbBuilder(CharsIO(), BytesIO())
            .create()
            .asMap().let { dbMap ->
                val testKey = StringBuffer("testkey")
                val testString = "LongTestString"
                dbMap[testKey] = testString.toByteArray()
                assertTrue { testString.toByteArray().contentEquals(dbMap[testKey]) }
                assertEquals(testString.toByteArray().size, dbMap[testKey]?.size)
                val testStringSmall = "STString"
                dbMap[testKey] = testStringSmall.toByteArray()
                Log.e("WhippetDBTest", " Size small: ${testStringSmall.toByteArray().size} sizeLong:${testString.toByteArray().size}  size read: ${dbMap[testKey]?.size }")
                assertTrue { testStringSmall.toByteArray().contentEquals(dbMap[testKey]) }
                assertEquals(testStringSmall.toByteArray().size, dbMap[testKey]?.size)
            }
    }
    @Test
    fun overwriteValueWithRemove() {
        DbBuilder(CharsIO(), BytesIO())
            .create()
            .asMap().let { dbMap ->
                val testKey = StringBuffer("testkey")
                val testString = "LongTestString"
                dbMap[testKey] = testString.toByteArray()
                assertTrue { testString.toByteArray().contentEquals(dbMap[testKey]) }
                assertEquals(testString.toByteArray().size, dbMap[testKey]?.size)
                val testStringSmall = "STString"
                dbMap.remove(testKey)
                dbMap[testKey] = testStringSmall.toByteArray()
                Log.e("WhippetDBTest", " Size small: ${testStringSmall.toByteArray().size} sizeLong:${testString.toByteArray().size}  size read: ${dbMap[testKey]?.size }")
                assertTrue { testStringSmall.toByteArray().contentEquals(dbMap[testKey]) }
                assertEquals(testStringSmall.toByteArray().size, dbMap[testKey]?.size)
            }
    }
}
```
And the result of the test is:
```
[1/2] WhippetDBTest#overwriteValue: FAILED (287ms)

STACKTRACE:
java.lang.AssertionError: Expected value to be true.
	at org.junit.Assert.fail(Assert.java:89)
	at kotlin.test.junit.JUnitAsserter.fail(JUnitSupport.kt:56)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:226)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:236)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.AssertionsKt__AssertionsKt.assertTrue(Assertions.kt:40)
	at kotlin.test.AssertionsKt.assertTrue(Unknown Source:1)
	at kotlin.test.AssertionsKt__AssertionsKt.assertTrue(Assertions.kt:34)
	at kotlin.test.AssertionsKt.assertTrue(Unknown Source:1)
	at kotlin.test.AssertionsKt__AssertionsKt.assertTrue$default(Assertions.kt:32)
	at kotlin.test.AssertionsKt.assertTrue$default(Unknown Source:1)
	at WhippetDBTest.overwriteValue(WhippetDBTest.kt:42)

[2/2] WhippetDBTest#overwriteValueWithRemove: PASSED (0ms)
```
Logs:
```
 I TestRunner: started: .WhippetDBTest)
 E WhippetDBTest:  Size small: 8 sizeLong:14  size read: 14
 E TestRunner: failed: .WhippetDBTest)
 E TestRunner: 	at com.bmwgroup.apinext.geocoder.test.WhippetDBTest.overwriteValue(WhippetDBTest.kt:42)
 I TestRunner: finished: .WhippetDBTest)
 I TestRunner: started: overwriteValueWithRemove(com.bmwgroup.apinext.geocoder.test.WhippetDBTest)
 E WhippetDBTest:  Size small: 8 sizeLong:14  size read: 8
 I TestRunner: finished: overwriteValueWithRemove(com.bmwgroup.apinext.geocoder.test.WhippetDBTest)
```
originally found on a filedatabase. I guess the size is not adapted on an overwrite action. I use ByteIO for Protobufs and realized that I got a lot of errors after I updated some values.

**Comment by samokhodkin** [comment]
> I guess the size is not adapted on an overwrite action

Yes, it was.

I posted a release 1.0.2 with this fix, not a maven central though

**Comment by GeniviAMmaintainer** [comment]
And even the test was used. Thank you very much, I am impressed with the speed!
